runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI:mongodb://mongolab-spherical-25892
  APP_ID:affinitize-parse-server
  MASTER_KEY:masterKey234
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  